# Generated by Django 4.1 on 2022-08-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('saldo_cuenta', models.IntegerField()),
                ('tipo_prestamo', models.CharField(max_length=50)),
                ('total_prestamo', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
