# Generated by Django 4.1 on 2022-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='numero',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id',
            field=models.IntegerField(db_column='id', default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
