# Generated by Django 4.1 on 2022-08-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datos_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
