# Generated by Django 4.1 on 2022-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tarjeta_numero_tarjeta_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': False},
        ),
    ]
