# Generated by Django 4.1 on 2022-08-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datos_actualizacion_datos_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos',
            new_name='Dato',
        ),
    ]
