# Generated by Django 4.1 on 2022-08-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cuenta_direccion_marcatarjeta_prestamo_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='marcatarjeta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipocuenta',
            options={'managed': True},
        ),
    ]
