# Generated by Django 4.1 on 2022-08-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cuenta_options_alter_direccion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.TextField()),
                ('numero', models.IntegerField()),
                ('ciudad', models.TextField()),
                ('provincia', models.TextField()),
                ('pais', models.TextField()),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MTarjetas',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_credito', models.TextField()),
            ],
            options={
                'db_table': 'm_tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tclien',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_des', models.TextField()),
            ],
            options={
                'db_table': 'Tclien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('descipcion', models.TextField()),
            ],
            options={
                'db_table': 'T_cuenta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='MarcaTarjeta',
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
        migrations.DeleteModel(
            name='Tiposclientes',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
