# Generated by Django 4.1 on 2022-08-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_direcciones_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direcciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mtarjetas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tclien',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tcuenta',
            options={'managed': False},
        ),
    ]
