# Generated by Django 4.1 on 2022-08-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_direcciones_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': True},
        ),
    ]
